/**
 * Topology -> AI page hydration queue.
 *
 * The wizard no longer writes deterministic placeholder/template page bodies
 * for missing routes. Missing topology pages are reported back to the builder
 * so the AI Builder can hydrate each route from user prompt/context.
 */

import type { GeneratedSitePlan, PageRouteNode } from '@/platform/core/siteTopologyPlanner';

function componentNameFromFilePath(filePath: string): string {
  const base = filePath.split('/').pop()?.replace(/\.(tsx|jsx|ts|js)$/i, '') || 'Page';
  return base.replace(/[^a-zA-Z0-9_$]/g, '') || 'Page';
}

function roleHeading(role: string, title: string): string {
  if (role === 'home') return title;
  return title || role.charAt(0).toUpperCase() + role.slice(1);
}

function buildFallbackPageModule(page: PageRouteNode): string {
  const componentName = componentNameFromFilePath(page.filePath);
  const heading = roleHeading(page.role, page.title);
  return `import React from 'react';

export default function ${componentName}() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="mx-auto max-w-5xl px-6 py-16">
        <h1 className="text-4xl font-bold tracking-tight">${heading}</h1>
        <p className="mt-4 text-muted-foreground">
          This page is ready for AI content generation.
        </p>
      </section>
    </main>
  );
}
`;
}

/**
 * Returns the topology pages whose target TSX files are not present in VFS.
 */
export function getMissingTopologyPages(
  plan: GeneratedSitePlan,
  existingFiles: Record<string, string>,
): PageRouteNode[] {
  return plan.pages.filter((page) => !existingFiles[page.filePath]);
}

/**
 * Returns non-home missing topology pages that should be generated by the AI
 * Builder instead of by deterministic route generation.
 */
export function getTopologyPagesForAIGeneration(
  plan: GeneratedSitePlan,
  existingFiles: Record<string, string>,
): PageRouteNode[] {
  return getMissingTopologyPages(plan, existingFiles).filter((page) => !page.isHome);
}

/**
 * Builds deterministic fallback files for topology pages missing in VFS.
 * These are safety-net modules to keep preview rendering stable.
 */
export function scaffoldMissingTopologyPages(
  plan: GeneratedSitePlan,
  existingFiles: Record<string, string>,
): Record<string, string> {
  const files: Record<string, string> = {};
  const missing = getMissingTopologyPages(plan, existingFiles);
  for (const page of missing) {
    files[page.filePath] = buildFallbackPageModule(page);
  }
  return files;
}
